<a href="https://colab.research.google.com/github/RogerHeederer/NLP_entry/blob/master/LSA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Reference Source : wikidocs.net 유영준님 자료

스스로 학습하면서 필요한 부분에는 추가적 설명, 소스 코드 삽입 및 수정 등이 있습니다. 영리적 목적이 아닌, 자기 계발 목적으로 정리한 자료입니다.


##Topic Modeling : 통계적 모델의 하나로, 텍스트 본문의 숨겨진 의미 구조를 파악하기 위해 사용되는 텍스트 마이닝 기법

**LSA는 토픽 모델링 분야에 아이디어를 제공한 알고리즘**

Latent Semantic Indexing or Latent Semantic Analysis

* 전치행렬, 단위행렬, 역행렬, 직교행렬, 대각행렬 개념이 나온다

* 절단된 SVD (Truncated SVD)를 사용

* 기존의 DTM이나 TF-IDF는 단어의 의미를 전혀 고려하지 못하는 단점. 그래서 LSA는 위 DTM, TF-IDF에 절단된 SVD를 적용해서 차원을 축소시키고, 단어들의 잠재적 의미를 이끌어낸다

In [17]:
import numpy as np
A=np.array([[0,0,0,1,0,1,1,0,0],[0,0,0,1,1,0,1,0,0],[0,1,1,0,2,0,0,0,0],[1,0,0,0,0,0,0,1,1]])
print(A)
np.shape(A) # 4*9 DTM Document Term Matrix


[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]


(4, 9)

In [5]:
U, s, VT = np.linalg.svd(A, full_matrices = True) #s 는 대각행렬 변수  VT 전치행렬 U 직교행렬

In [14]:
print(U.round(2), '\n\n', s.round(2), '\n\n', VT.round(2)) # 소수점 2째자리까지만

[[-0.24  0.75  0.   -0.62]
 [-0.51  0.44 -0.    0.74]
 [-0.83 -0.49 -0.   -0.27]
 [-0.   -0.    1.    0.  ]] 

 [2.69 2.05 1.73 0.77] 

 [[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]
 [ 0.58 -0.    0.    0.   -0.    0.   -0.    0.58  0.58]
 [ 0.   -0.35 -0.35  0.16  0.25 -0.8   0.16 -0.   -0.  ]
 [-0.   -0.78 -0.01 -0.2   0.4   0.4  -0.2   0.    0.  ]
 [-0.29  0.31 -0.78 -0.24  0.23  0.23  0.01  0.14  0.14]
 [-0.29 -0.1   0.26 -0.59 -0.08 -0.08  0.66  0.14  0.14]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19  0.75 -0.25]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19 -0.25  0.75]]


In [15]:
S = np.zeros((4,9)) 
S[:4, :4] = np.diag(s)
print(S.round(2))
np.shape(S)

# 특이값 리스트 s를 행렬 형태료 편경  2.69 > 2.05 >1.73 > 0.77 내림차순 확인

[[2.69 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   2.05 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   1.73 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.77 0.   0.   0.   0.   0.  ]]


(4, 9)

In [16]:
print(VT.round(2))
np.shape(VT)

[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]
 [ 0.58 -0.    0.    0.   -0.    0.   -0.    0.58  0.58]
 [ 0.   -0.35 -0.35  0.16  0.25 -0.8   0.16 -0.   -0.  ]
 [-0.   -0.78 -0.01 -0.2   0.4   0.4  -0.2   0.    0.  ]
 [-0.29  0.31 -0.78 -0.24  0.23  0.23  0.01  0.14  0.14]
 [-0.29 -0.1   0.26 -0.59 -0.08 -0.08  0.66  0.14  0.14]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19  0.75 -0.25]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19 -0.25  0.75]]


(9, 9)

In [18]:
#U × S × VT를 하면 기존의 행렬 A가 나와야 함.
# Full SVD 수행물
np.allclose(A, np.dot(np.dot(U,S), VT).round(2)) #allclose()는 2개의 행렬이 동일하면 True 반환

True

In [19]:
# 절단된 SVD 수행

S = S[:2,:2] # 상위 2개만 남기고 제거
print(S.round(2))

[[2.69 0.  ]
 [0.   2.05]]


In [21]:
U = U[:,:2]
print(U.round(2))

[[-0.24  0.75]
 [-0.51  0.44]
 [-0.83 -0.49]
 [-0.   -0.  ]]


In [22]:
VT=VT[:2,:] # 전치행렬 2개의 행만 남기고 제거, V 관점에서는 2개의 열만 남기고 제거한 거랑 같음
print(VT.round(2))

[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]]


In [23]:
A_prime = np.dot(np.dot(U,S), VT)
print(A)
print(A_prime.round(2))

[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]
[[ 0.   -0.17 -0.17  1.08  0.12  0.62  1.08 -0.   -0.  ]
 [ 0.    0.2   0.2   0.91  0.86  0.45  0.91  0.    0.  ]
 [ 0.    0.93  0.93  0.03  2.05 -0.17  0.03  0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.  ]]


**사이킷런을 통한 토픽 모델링 실습**

LSA를 사용해서 원하는 토픽의 수로 압축하고, 각 토픽당 가장 중요한 단어 5개 출력

In [25]:
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
dataset = fetch_20newsgroups(shuffle=True, random_state=1, remove=('headers', 'footers', 'quotes'))
documents = dataset.data

In [27]:
len(documents)

11314

In [28]:
documents[1]

"\n\n\n\n\n\n\nYeah, do you expect people to read the FAQ, etc. and actually accept hard\natheism?  No, you need a little leap of faith, Jimmy.  Your logic runs out\nof steam!\n\n\n\n\n\n\n\nJim,\n\nSorry I can't pity you, Jim.  And I'm sorry that you have these feelings of\ndenial about the faith you need to get by.  Oh well, just pretend that it will\nall end happily ever after anyway.  Maybe if you start a new newsgroup,\nalt.atheist.hard, you won't be bummin' so much?\n\n\n\n\n\n\nBye-Bye, Big Jim.  Don't forget your Flintstone's Chewables!  :) \n--\nBake Timmons, III"

In [32]:
print(dataset.target_names) #어떤 20개의 카테고리를 가지고 있었는지 확인

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [35]:
# 텍스트 전처리 하기

news_df = pd.DataFrame({'document':documents})
news_df[1:5]

document
1  \n\n\n\n\n\n\nYeah, do you expect people to re...
2  Although I realize that principle is not one o...
3  Notwithstanding all the legitimate fuss about ...
4  Well, I will have to change the scoring on my ...

In [37]:
news_df['clean_doc'] = news_df['document'].str.replace("[^a-zA-Z]", " ") #특수문자 제거
news_df[1:5]

document                                          clean_doc
1  \n\n\n\n\n\n\nYeah, do you expect people to re...         Yeah  do you expect people to read the ...
2  Although I realize that principle is not one o...  Although I realize that principle is not one o...
3  Notwithstanding all the legitimate fuss about ...  Notwithstanding all the legitimate fuss about ...
4  Well, I will have to change the scoring on my ...  Well  I will have to change the scoring on my ...

In [38]:
news_df['clean_doc'] = news_df['clean_doc'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3])) #길이가 3이하 단어 제거
news_df['clean_doc'][1:5]

1    Yeah expect people read actually accept hard a...
2    Although realize that principle your strongest...
3    Notwithstanding legitimate fuss about this pro...
4    Well will have change scoring playoff pool Unf...
Name: clean_doc, dtype: object

In [39]:
news_df['clean_doc'] = news_df['clean_doc'].apply(lambda x: x.lower()) #소문자로 바꾸기
news_df['clean_doc'][1:5]

1    yeah expect people read actually accept hard a...
2    although realize that principle your strongest...
3    notwithstanding legitimate fuss about this pro...
4    well will have change scoring playoff pool unf...
Name: clean_doc, dtype: object

In [42]:
#토큰화 수행 후 불용어 제거하기
import nltk
nltk.download('stopwords')
  
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
tokenized_doc = news_df['clean_doc'].apply(lambda x: x.split())
tokenized_doc[1:5]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


1    [yeah, expect, people, read, actually, accept,...
2    [although, realize, that, principle, your, str...
3    [notwithstanding, legitimate, fuss, about, thi...
4    [well, will, have, change, scoring, playoff, p...
Name: clean_doc, dtype: object

In [43]:
tokenized_doc = tokenized_doc.apply(lambda x: [item for item in x if item not in stop_words])

In [45]:
print(tokenized_doc[1]) # 토큰화 수행 후 your about just 등 불용어 제거됨

['yeah', 'expect', 'people', 'read', 'actually', 'accept', 'hard', 'atheism', 'need', 'little', 'leap', 'faith', 'jimmy', 'logic', 'runs', 'steam', 'sorry', 'pity', 'sorry', 'feelings', 'denial', 'faith', 'need', 'well', 'pretend', 'happily', 'ever', 'anyway', 'maybe', 'start', 'newsgroup', 'atheist', 'hard', 'bummin', 'much', 'forget', 'flintstone', 'chewables', 'bake', 'timmons']


In [46]:
# TF-IDF는 토큰화가 되어 있지 않은 텍스트 데이터를 입력으로 사용하기 때문에, 다시 역토큰화(detoken~~) 해야한다.
detokenized_doc = []
for i in range(len(news_df)):
  t = ' '.join(tokenized_doc[i])
  detokenized_doc.append(t)

news_df['clean_doc'] = detokenized_doc
news_df['clean_doc'][1]

'yeah expect people read actually accept hard atheism need little leap faith jimmy logic runs steam sorry pity sorry feelings denial faith need well pretend happily ever anyway maybe start newsgroup atheist hard bummin much forget flintstone chewables bake timmons'

In [48]:
# 사이킷 런의 TfidfVectorizer를 통해 단어 1000개에 대한 TF-IDF 행렬 만든다.
# 1000개 단어로 제한해서 실습해보겠음

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english', max_features = 1000, max_df = 0.5, smooth_idf=True)
X = vectorizer.fit_transform(news_df['clean_doc'])

In [55]:
X.shape

(11314, 1000)

**토픽 모델링하기**

In [57]:
from sklearn.decomposition import TruncatedSVD
svd_model = TruncatedSVD(n_components=20, algorithm='randomized', n_iter=100, random_state=122)
svd_model.fit(X)
len(svd_model.components_) #svd_model.components_ 이건 LSA의 VT에 해당 전치행렬

20

In [58]:
np.shape(svd_model.components_) #사전에 정의한 토픽수 20개. 단어수 1000개

(20, 1000)

In [60]:
svd_model.components_

array([[ 0.01469447,  0.05019033,  0.02132607, ...,  0.07865965,
         0.01432356,  0.01788786],
       [-0.00535706,  0.01653897, -0.01644943, ..., -0.0635444 ,
        -0.01063538, -0.01905089],
       [ 0.00172364, -0.00364954, -0.01799981, ...,  0.05876243,
         0.0262722 ,  0.02236444],
       ...,
       [-0.01119135,  0.00486264,  0.00307659, ...,  0.01869445,
        -0.00064808,  0.00032117],
       [ 0.00206029,  0.01546828,  0.01100956, ..., -0.09165235,
        -0.00111648, -0.00530245],
       [ 0.00197576, -0.03695809, -0.00546641, ...,  0.03533267,
        -0.01475702, -0.0039975 ]])

In [63]:
terms = vectorizer.get_feature_names() # 단어 집합. 1,000개의 단어가 저장됨.

def get_topics(components, feature_names, n=5):
    for idx, topic in enumerate(components):
        print("Topic %d:" % (idx+1), [(feature_names[i], topic[i].round(5)) for i in topic.argsort()[:-n - 1:-1]])

In [64]:
get_topics(svd_model.components_, terms)

Topic 1: [('like', 0.21386), ('know', 0.20046), ('people', 0.19293), ('think', 0.17805), ('good', 0.15128)]
Topic 2: [('thanks', 0.32888), ('windows', 0.29088), ('card', 0.18069), ('drive', 0.17455), ('mail', 0.15111)]
Topic 3: [('game', 0.37064), ('team', 0.32443), ('year', 0.28154), ('games', 0.2537), ('season', 0.18419)]
Topic 4: [('drive', 0.53324), ('scsi', 0.20165), ('hard', 0.15628), ('disk', 0.15578), ('card', 0.13994)]
Topic 5: [('windows', 0.40399), ('file', 0.25436), ('window', 0.18044), ('files', 0.16078), ('program', 0.13894)]
Topic 6: [('chip', 0.16114), ('government', 0.16009), ('mail', 0.15625), ('space', 0.1507), ('information', 0.13562)]
Topic 7: [('like', 0.67086), ('bike', 0.14236), ('chip', 0.11169), ('know', 0.11139), ('sounds', 0.10371)]
Topic 8: [('card', 0.46633), ('video', 0.22137), ('sale', 0.21266), ('monitor', 0.15463), ('offer', 0.14643)]
Topic 9: [('know', 0.46047), ('card', 0.33605), ('chip', 0.17558), ('government', 0.1522), ('video', 0.14356)]
Topic 10

LSA는 문서의 유사도 계산을 빠르고 쉽게 구현이 가능한 장점을 가진다.

하지만 새로운 데이터가 추가되면 처음부터 계산을 다시 해야 하기 때문에 업데이트가 어렵다.

그래서 Word2Vec 등 단어의 의미를 벡터화할 수 있는 방법론이 각광받고 있다. 