<a href="https://colab.research.google.com/github/RogerHeederer/NLP_entry/blob/master/SplittingData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Reference Source : wikidocs.net 유영준님 자료

스스로 학습하면서 필요한 부분에는 추가적 설명, 소스 코드 삽입 및 수정 등이 있습니다. 영리적 목적이 아닌, 자기 계발 목적으로 정리한 자료입니다.

In [1]:
X,y = zip(['a', 1], ['b', 2], ['c', 3])
# 동일 개수 시퀀스 자료형에서 각 순서에 등장하는 원소끼리 묶어주는 역할
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


In [3]:
sequences=[['a', 1], ['b', 2], ['c', 3]]
X, y = zip(*sequences)
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


In [4]:
import pandas as pd

values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']

df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [5]:
X = df['메일 본문']
y = df['스팸 메일 유무']

print(X)

0          당신에게 드리는 마지막 혜택!
1      내일 뵐 수 있을지 확인 부탁드...
2      도연씨. 잘 지내시죠? 오랜만입...
3    (광고) AI로 주가를 예측할 수 있다!
Name: 메일 본문, dtype: object


In [6]:
print(y)

0    1
1    0
2    0
3    1
Name: 스팸 메일 유무, dtype: int64


**Numpy 사용해서 분리하기**

In [8]:
import numpy as np
ar = np.arange(0,16).reshape((4,4))
print(ar)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [9]:
X = ar[:, :3]

In [10]:
print(X)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [11]:
y=ar[:,3]
print(y)

[ 3  7 11 15]


**사이킷 런 이용해서 분리**

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)
#테스트 사이즈나 트레인 사이즈 둘 중 하나만 기재하면 해당 비율로 알아서 나눠줌
#random_state : 난수 시드

In [13]:
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5,2)), range(5)

In [14]:
print(X)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [16]:
print(y), print(list(y))

range(0, 5)
[0, 1, 2, 3, 4]


(None, None)

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1234)
#random_state 지정으로 인해 순서가 섞인 후 훈련,테스트 데이터 나눠짐

In [24]:
print(X_train,'\n'),print(X_test)

[[2 3]
 [4 5]
 [6 7]] 

[[8 9]
 [0 1]]


(None, None)

[[8 9]
 [0 1]]


In [25]:
print(y_train,'\n'), print(y_test)

[1, 2, 3] 

[4, 0]


(None, None)

#수동으로 한땀 한땀 분리

In [31]:
X, y = np.arange(0,24).reshape((12,2)), range(12)
print(X)
print(X.shape)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
(12, 2)


In [28]:
print(list(y))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [30]:
# 유의할 점!
n_of_train = int(len(X) * 0.8)
n_of_test = int(len(X) - n_of_train)
print(n_of_train, n_of_test)

9 3


### 위 코드에서 유의할 점###
트레인 데이터에 0.8 곱했으니 나머지는 0.2 곱해야지 생각하면 안됨.

4,518 * 0.8 = 3614.4 == 3614( 소수점내림)

4,518 * 0.2 = 903.6 == 903 (소수점 내림)

두개 더하면 4517개임. 데이터 1개 누락 생김

그래서 어느 한 쪽 계산 후 빼주는 방식으로 나머지 값을 산정해야 함

In [34]:
X_test = X[n_of_train:] #전체 데이터 중에서 20%만큼 뒤의 데이터 저장
y_test = y[n_of_train:] #전체 데이터 중에서 20%만큼 뒤의 데이터 저장
X_train = X[:n_of_train] #전체 데이터 중에서 80%만큼 앞의 데이터 저장
y_train = y[:n_of_train] #전체 데이터 중에서 80%만큼 앞의 데이터 저장

In [35]:
X_test.shape

(3, 2)

In [36]:
X_train.shape

(9, 2)

In [37]:
print(X_test)

[[18 19]
 [20 21]
 [22 23]]


In [38]:
print(list(y_test))

[9, 10, 11]
