<a href="https://colab.research.google.com/github/RogerHeederer/NLP_entry/blob/master/VectorMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Reference Source : wikidocs.net 유영준님 자료

스스로 학습하면서 필요한 부분에는 추가적 설명, 소스 코드 삽입 및 수정 등이 있습니다. 영리적 목적이 아닌, 자기 계발 목적으로 정리한 자료입니다.


In [2]:
import numpy as np
#0차원 텐서 = 스칼라
d = np.array(5)
d.ndim, d.shape #0차원, 크기없음

(0, ())

In [3]:
#숫자를 특정 순서대로 배열한 것을 벡터라 함, 벡터를 1차원 텐서라고도 함
# 벡터의 차원과 텐서의 차원은 다른 개념

d = np.array([1,2,3,4])
print(d.ndim)
print(d.shape)
# 4차원 벡터, 1차원 텐서

1
(4,)


벡터에서의 차원은 하나의 축에 차원들이 존재.

텐서에서의 차원은 축의 개수

In [6]:
# 행과 열이 존재하는 벡터의 배열 = 행렬 = 2차원 텐서

d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(d.ndim)
print(d.shape)
print(d)

2
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
# 3차원 텐서
# 행렬(2차원텐서)를 단위로 한 번 더 배열해버리면 3차원 텐서가 됨
# 보통 3차원 이상의 배열부터 텐서라고 부른다.(데이터 사이언스 분야에서)

d = np.array( [ [ [1,2,3,4,5],[6,7,8,9,10],[10,11,12,13,14] ],
                [ [15,16,17,18,19],[19,20,21,22,23],[23,24,25,26,27] ]
               ])
#2개의 큰 데이터가 있는데, 각각은 3개의 작은 데이터로 구성되고, 그 3개의 데이터는 더 작은 5개의 데이터로 구성
print(d.ndim)
print(d.shape)

3
(2, 3, 5)


3D 텐서는 시퀀스 데이터를 표현할 때 자주 사용. 주로 문서, 아티클, 텍스트 등. 

3D 텐서는 (samples, timesteps, word_dim)

배치 개념에서는 (batch_size, timesteps, word_dim)

훈련데이터를 묶어서 한 꺼번에 입력으로 사용하는 것을 배치